# version: "3.9"
name: next-blogger

services:
  next-redis:
    container_name: next-redis
    image: redis:7.2.7
    expose:
      - "6379"
  next-blogger:
    image: next-blogger:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-blogger
    ports:
      - "3010:3000"
    environment:
      PORT: 3000
      REDIS_URL: redis://next-redis:6379
    depends_on:
      next-redis:
        condition: service_started
