# version: "3.9"
name: next-blogger

services:
  next-blogger:
    image: next-blogger:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-blogger
    networks:
      - dokploy-network # 必须加，Dokploy 靠这个路由
    ports:
      - 3001
    environment:
      PORT: 3001
      REDIS_URL: redis://redis:6379

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dokploy-network:
    external: true
