# version: "3.9"
name: next-blogger

services:
  next-redis:
    container_name: next-redis
    image: redis:7.2.7
    ports:
      - 6379
    networks:
      - next-blogger-network
  next-blogger:
    image: next-blogger:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-blogger
    networks:
      - next-blogger-network
    ports:
      - 3000
    environment:
      PORT: 3000
      REDIS_URL: redis://next-redis:6379
    depends_on:
      next-redis:
        condition: service_started

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  next-blogger-network:
    external: true
